# @category GCL

import cp
from ghidra.program.flatapi import FlatProgramAPI
from ghidra.program.model.symbol import SourceType

GN_VISIBLE = 0x1000

# Constantes SN_ (Set Name flags)
SN_CHECK = 0x01  # Fail if the name contains invalid characters
SN_NOCHECK = 0x02  # Don't fail, replace invalid chars with '_'
SN_PUBLIC = 0x04  # Make name public
SN_NON_PUBLIC = 0x08  # Make name non-public
SN_WEAK = 0x10  # Make name weak
SN_NON_WEAK = 0x20  # Make name non-weak
SN_AUTO = 0x40  # Make name autogenerated
SN_NON_AUTO = 0x80  # Make name non-autogenerated
SN_NOLIST = 0x100  # Exclude from name list
SN_NOWARN = 0x200  # Don't display warnings
SN_LOCAL = 0x400  # Create local name


def get_name(ea, flags):
    fcp = FlatProgramAPI(cp.currentProgram)
    listing = cp.currentProgram.getListing()
    minAddress = cp.currentProgram.minAddress.getOffset()
    codeUnit = listing.getCodeUnitAt(fcp.toAddr(minAddress + ea))
    ret = str()
    if codeUnit != None:
        name = codeUnit.getSymbols()
        if len(name):
            ret = str(name[0])
    return ret


def set_name(ea, name, flags=0):
    """
    Set or delete name of an item at the specified address.

    @param ea: linear address. do nothing if ea is not valid (return 0).
               tail bytes can't have names.
    @param name: new name.
                 * None: do nothing (return 0).
                 * "": delete name.
                 * otherwise this is a new name.
    @param flags: Set name flags. If a bit is not specified, then the
                  corresponding action is not performed and the name will
                  retain the same bits as before calling this function.
                  For new names, default is: non-public, non-weak, non-auto.
    @retval 1: ok, name is changed
    @retval 0: failure, a warning is displayed
    """

    # Handle None case - do nothing (return 0)
    if name is None:
        return 0

    try:
        fcp = FlatProgramAPI(cp.currentProgram)
        listing = cp.currentProgram.getListing()
        symbol_table = cp.currentProgram.getSymbolTable()
        minAddress = cp.currentProgram.minAddress.getOffset()

        # Convert ea to address (siguiendo tu patrón existente)
        addr = fcp.toAddr(minAddress + ea)

        # Check if address is valid (do nothing if ea is not valid)
        if not cp.currentProgram.getMemory().contains(addr):
            return 0

        # Check if it's a tail byte (can't have names)
        if _is_tail_byte(addr, listing):
            return 0

        # Start transaction (siguiendo el patrón de tu código)
        transaction_id = cp.currentProgram.startTransaction("Set Name")

        try:
            if name == "":
                # Delete name
                result = _delete_name(addr, symbol_table, flags)
            else:
                # Set new name
                result = _set_new_name(addr, name, symbol_table, flags)

            cp.currentProgram.endTransaction(transaction_id, True)
            return result

        except Exception as e:
            cp.currentProgram.endTransaction(transaction_id, False)
            if not (flags & SN_NOWARN):
                print("Error setting name: " + str(e))
            return 0

    except Exception as e:
        if not (flags & SN_NOWARN):
            print("Error in set_name: " + str(e))
        return 0


def _is_tail_byte(addr, listing):
    """
    Check if address is a tail byte (part of a multi-byte instruction/data)
    Tail bytes can't have names in IDA Pro
    """
    # Check if it's in the middle of an instruction
    instruction = listing.getInstructionContaining(addr)
    if instruction and not instruction.getAddress().equals(addr):
        return True

    # Check if it's in the middle of defined data
    data = listing.getDefinedDataContaining(addr)
    if data and not data.getAddress().equals(addr):
        return True

    return False


def _delete_name(addr, symbol_table, flags):
    """Delete name at address"""
    symbols = symbol_table.getSymbols(addr)
    deleted = False

    for symbol in symbols:
        # Only delete labels (not function names, etc.)
        if symbol.getSymbolType().name() == "LABEL":
            symbol.delete()
            deleted = True

    return 1 if deleted else 0


def _set_new_name(addr, name, symbol_table, flags):
    """Set new name at address"""

    # Validate name if SN_CHECK is set
    if flags & SN_CHECK:
        if not _is_valid_name(name):
            if not (flags & SN_NOWARN):
                print("Invalid name: " + name)
            return 0

    # Clean name if SN_NOCHECK is set
    if flags & SN_NOCHECK:
        name = _clean_name(name)

    # Get existing symbol to preserve properties
    existing_symbol = None
    symbols = symbol_table.getSymbols(addr)
    for symbol in symbols:
        if symbol.getSymbolType().name() == "LABEL":
            existing_symbol = symbol
            break

    # Determine source type based on flags
    source_type = _determine_source_type(flags, existing_symbol)

    # Determine namespace (local vs global)
    namespace = _determine_namespace(addr, flags, existing_symbol)
    if namespace is None and (flags & SN_LOCAL):
        if not (flags & SN_NOWARN):
            print("Cannot create local name: no function at address")
        return 0

    # Remove existing symbol if we're replacing it
    if existing_symbol:
        existing_symbol.delete()

    try:
        # Create new symbol
        if namespace:
            symbol = symbol_table.createLabel(addr, name, namespace, source_type)
        else:
            symbol = symbol_table.createLabel(addr, name, source_type)

        if symbol is None:
            if not (flags & SN_NOWARN):
                print("Failed to create symbol")
            return 0

        return 1

    except Exception as e:
        if not (flags & SN_NOWARN):
            print("Error creating symbol: " + str(e))
        return 0


def _is_valid_name(name):
    """Check if name contains only valid characters"""
    if not name:
        return True

    import re

    # Basic validation - starts with letter/underscore, contains only alphanumeric/underscore
    valid_pattern = r"^[a-zA-Z_][a-zA-Z0-9_]*$"
    return bool(re.match(valid_pattern, name))


def _clean_name(name):
    """Replace invalid characters with underscore"""
    import re

    # Replace any non-alphanumeric character (except underscore) with underscore
    cleaned = re.sub(r"[^a-zA-Z0-9_]", "_", name)

    # Ensure it starts with letter or underscore
    if cleaned and not re.match(r"^[a-zA-Z_]", cleaned):
        cleaned = "_" + cleaned

    return cleaned


def _determine_source_type(flags, existing_symbol):
    """
    Determine source type based on flags and existing symbol
    Default for new names: non-auto (USER_DEFINED)
    """
    if flags & SN_AUTO:
        return SourceType.ANALYSIS
    elif flags & SN_NON_AUTO:
        return SourceType.USER_DEFINED
    elif existing_symbol:
        # Preserve existing source type if not specified
        return existing_symbol.getSource()
    else:
        # Default for new names: non-auto
        return SourceType.USER_DEFINED


def _determine_namespace(addr, flags, existing_symbol):
    """Determine namespace (local vs global) based on flags"""
    if flags & SN_LOCAL:
        # Find containing function for local scope
        func = cp.currentProgram.getFunctionManager().getFunctionContaining(addr)
        return func if func else None
    elif existing_symbol and not (flags & (SN_LOCAL | SN_PUBLIC | SN_NON_PUBLIC)):
        # Preserve existing namespace if not specified
        return existing_symbol.getParentNamespace()
    else:
        # Default to global namespace
        return cp.currentProgram.getGlobalNamespace()
