# @category GCL

import cp
from ghidra.program.flatapi import FlatProgramAPI
from ghidra.program.model.symbol import SourceType
from ghidra.util.exception import DuplicateNameException, InvalidInputException
from ghidra.program.model.address import Address

# Constantes SN_ (Set Name flags)
SN_CHECK = 0x00  # Fail if the name contains invalid characters.
SN_NOCHECK = 0x01  # Don't fail, replace invalid chars with '_'
SN_PUBLIC = 0x02  # Make name public
SN_NON_PUBLIC = 0x04  # Make name non-public
SN_WEAK = 0x08  # Make name weak
SN_NON_WEAK = 0x10  # Make name non-weak
SN_AUTO = 0x20  # Make name autogenerated
SN_NON_AUTO = 0x40  # Make name non-autogenerated
SN_NOLIST = 0x80  # Exclude from name list
SN_NOWARN = 0x100  # don't display a warning if failed
SN_LOCAL = 0x200  # Create local name
SN_IDBENC = 0x400  # the name is given in the IDB encoding; non-ASCII bytes will be decoded accordingly
SN_FORCE = 0x800  # if the specified name is already present in the database, try variations with a numerical suffix like "_123"
SN_NODUMMY = 0x1000  # automatically prepend the name with '_' if it begins with a dummy suffix such as 'sub_'.
SN_DELTAIL = (
    0x2000  # if name cannot be set because of a tail byte, delete the hindering item
)


def get_name(ea, flags):
    fcp = FlatProgramAPI(cp.currentProgram)
    listing = cp.currentProgram.getListing()
    minAddress = cp.currentProgram.minAddress.getOffset()
    codeUnit = listing.getCodeUnitAt(fcp.toAddr(ea))
    ret = str()
    if codeUnit != None:
        name = codeUnit.getSymbols()
        if len(name):
            ret = str(name[0])
    return ret


def set_name(ea, name, flags=0):
    """
    Changes the primary symbol name at the given address `ea`, following naming rules and flags.

    :param ea: linear address (int)
    :param name: new name (str), None or "" to delete the name
    :param flags: integer flags with combined SN_* bits
    :returns: 1 if successful, 0 if it fails or does nothing
    """

    if name is None:
        return 0

    program = cp.currentProgram  # ✅ Igual que get_name
    addr_factory = program.getAddressFactory()

    # Validar dirección
    try:
        addr = addr_factory.getDefaultAddressSpace().getAddress(ea)
    except Exception:
        if not (flags & SN_NOWARN):
            print(f"Warning: invalid address {ea}")
        return 0

    if addr is None:
        return 0

    # Obtener symbol table
    symbol_table = program.getSymbolTable()

    # Validar nombre si SN_CHECK está activo
    import re

    if not (flags & SN_NOCHECK):
        if not re.match(r"^[a-zA-Z_][a-zA-Z0-9_]*$", name) and name != "":
            if not (flags & SN_NOWARN):
                print(f"Warning: invalid name '{name}' contains invalid characters")
            return 0
    else:
        if name != "":
            name = re.sub(r"[^a-zA-Z0-9_]", "_", name)
            if name and not re.match(r"^[a-zA-Z_]", name):
                name = "_" + name

    # Buscar símbolo existente
    existing_symbols = symbol_table.getSymbols(addr)
    primary_symbol = next((sym for sym in existing_symbols if sym.isPrimary()), None)

    try:
        # Eliminar nombre
        if name == "":
            if primary_symbol is not None:
                symbol_table.removeSymbolSpecial(primary_symbol)
            return 1

        # Aplicar SN_NODUMMY
        if flags & SN_NODUMMY:
            dummy_prefixes = [
                "sub_",
                "loc_",
                "unk_",
                "byte_",
                "word_",
                "dword_",
                "qword_",
            ]
            if any(name.startswith(prefix) for prefix in dummy_prefixes):
                name = "_" + name

        # Generar nombre único si SN_FORCE está activo
        original_name = name
        counter = 0
        if flags & SN_FORCE:
            while symbol_table.getSymbol(name, addr.getAddressSpace()) is not None:
                counter += 1
                name = f"{original_name}_{counter}"

        # Determinar namespace
        if flags & SN_LOCAL:
            function_manager = program.getFunctionManager()
            containing_function = function_manager.getFunctionContaining(addr)
            if containing_function is not None:
                namespace = containing_function.getName()
            else:
                namespace = program.getNamespaceManager().getGlobalNamespace()
        else:
            namespace = program.getNamespaceManager().getGlobalNamespace()

        # Determinar SourceType
        source_type = (
            SourceType.DEFAULT if (flags & SN_AUTO) else SourceType.USER_DEFINED
        )

        # Crear o actualizar símbolo
        if primary_symbol:
            primary_symbol.setName(name, source_type)
            new_symbol = primary_symbol
        else:
            new_symbol = symbol_table.createLabel(addr, name, namespace, source_type)

        if new_symbol is None:
            if not (flags & SN_NOWARN):
                print(f"Warning: could not create/update symbol '{name}' at {addr}")
            return 0

        # Aplicar flags adicionales
        if flags & SN_PUBLIC:
            new_symbol.setGlobal()

        return 1

    except DuplicateNameException:
        if not (flags & SN_NOWARN):
            print(f"Warning: the name '{name}' already exists.")
        return 0
    except InvalidInputException:
        if not (flags & SN_NOWARN):
            print(f"Warning: invalid name '{name}'.")
        return 0
    except Exception as e:
        if not (flags & SN_NOWARN):
            print(f"Warning: unexpected error: {str(e)}")
        return 0


# Helper functions to use flags more easily
def set_name_checked(ea, name):
    """Set name with character validation"""
    return set_name(ea, name, SN_CHECK)


def set_name_unchecked(ea, name):
    """Set name replacing invalid characters"""
    return set_name(ea, name, SN_NOCHECK)


def set_name_public(ea, name):
    """Set public name"""
    return set_name(ea, name, SN_PUBLIC | SN_NOCHECK)


def set_name_local(ea, name):
    """Set name local to the function"""
    return set_name(ea, name, SN_LOCAL | SN_NOCHECK)


def set_name_auto(ea, name):
    """Set auto-generated name"""
    return set_name(ea, name, SN_AUTO | SN_NOCHECK)


def set_name_force(ea, name):
    """Set name forcing variations if it already exists"""
    return set_name(ea, name, SN_FORCE | SN_NOCHECK)


__all__ = [
    "set_name",
    "get_name",
    "SN_CHECK",
    "SN_NOCHECK",
    "SN_PUBLIC",
    "SN_NON_PUBLIC",
    "SN_WEAK",
    "SN_NON_WEAK",
    "SN_AUTO",
    "SN_NON_AUTO",
    "SN_NOLIST",
    "SN_NOWARN",
    "SN_LOCAL",
    "SN_IDBENC",
    "SN_FORCE",
    "SN_NODUMMY",
    "SN_DELTAIL",
]
